### ISSUE TITLE
An error occurred while installing ./dist/drozer-2.4.3-py2-none-any.whl --hash=sha256:07dd02dea57ceadecfa90d9f01ba0f690a7c8ada084be152132f8564e062d5c6 --hash=sha256:b5776c8697a03e46bb46634e97b0103ff6460155c35584ad5e3c6d1d921c69a7

### ISSUE THREAD

**Issue by chevyphillip** [fujiokayu/Installing-Drozer-on-macOS-Catalina#1]
pipenv install dist/drozer-2.4.3-py2-none-any.whl
Installing dist/drozer-2.4.3-py2-none-any.whl…
Adding drozer to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (5c3dbd)!
Installing dependencies from Pipfile.lock (5c3dbd)…
An error occurred while installing ./dist/drozer-2.4.3-py2-none-any.whl --hash=sha256:07dd02dea57ceadecfa90d9f01ba0f690a7c8ada084be152132f8564e062d5c6 --hash=sha256:b5776c8697a03e46bb46634e97b0103ff6460155c35584ad5e3c6d1d921c69a7! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 8/8 — 00:00:07
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 1983, in do_install
[pipenv.exceptions.InstallError]:       do_init(
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 1246, in do_init
[pipenv.exceptions.InstallError]:       do_install_dependencies(
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 858, in do_install_dependencies
[pipenv.exceptions.InstallError]:       batch_install(
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: []
[pipenv.exceptions.InstallError]: ['ERROR: drozer-2.4.3-py2-none-any.whl is not a supported wheel on this platform.']
ERROR: ERROR: Package installation failed...

**Comment by fujiokayu** [comment]
@chevonmdphillip 

Thank you for report this issue.

> [pipenv.exceptions.InstallError]: ['ERROR: drozer-2.4.3-py2-none-any.whl is not a supported wheel on this platform.']

This can be caused by different Python versions from required one.  
Can you tell me information the following: 

- `python_version` wrote in your Pipfile
- return value of thise cmd in state of `pipenv shell`:
  - `python --version`
  - `python2 --version`

**Comment by fujiokayu** [comment]
Closed due to no reply for a while.
