### ISSUE TITLE
[Ernno 2] No such file or directory

### ISSUE THREAD

**Issue by jdonsec** [fujiokayu/Installing-Drozer-on-macOS-Catalina#2]
Environment
Operating system: OS Catalina

Java Version: 1.7.0_80

Android Version: 10

Install Method: https://github.com/fujiokayu/Installing-Drozer-on-macOS-Catalina

Drozer Version: 2.4.4

I keep getting the error 2 as well.

[Errno 2] No such file or directory

**Comment by fujiokayu** [comment]
@jdonsec 

Thank you for reporting this issue.
And sorry, Now I don't have Android 10 device, so I will confirm that later. (maybe, I will confirm in this week.)

**Comment by fujiokayu** [comment]
@jdonsec 
I checked it on an Android 10 device and it worked fine in my environment.

If possible, could you tell me the result of running the command `pip list --local` after doing `pipenv shell`?
And I want to make sure that the libraries listed in the [prerequisites](https://github.com/FSecureLABS/drozer#prerequisites) are installed.

**Comment by fujiokayu** [comment]
Closed due to no reply for a while.
