### ISSUE TITLE
Getting SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vinilnarayan** [fujiokayu/Installing-Drozer-on-macOS-Catalina#3]
Hi,
I'm using Mac OS Big Sur, and I have completed until step 6 in https://github.com/fujiokayu/Installing-Drozer-on-macOS-Catalina.
While executing 7th step, I'm getting a SyntaxError like below. Kindly help me to resolve this issue
<img width="814" alt="Screenshot 2022-03-23 at 12 58 25 AM" src="https://user-images.githubusercontent.com/46709848/159560956-3dc685b4-852f-4a92-83ce-40f146e0839c.png">
.   

```
Vinils-MBP:drozer vinilnarayan$ python --version
Python 2.7.16
Vinils-MBP:drozer vinilnarayan$ pipenv shell
Launching subshell in virtual environment...

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$  . /Users/vinilnarayan/.local/share/virtualenvs/drozer-zG0EXZKL/bin/activate
(drozer) bash-3.2$ python setup.py bdist_wheel
Traceback (most recent call last):
  File "/Users/vinilnarayan/Mac_BackUP/Downloads/Tools/drozer/setup.py", line 8, in <module>
    from src.drozer import meta
  File "/Users/vinilnarayan/Mac_BackUP/Downloads/Tools/drozer/src/drozer/meta.py", line 63
    print "%s %s\n" % (name, version)
          ^
SyntaxError: invalid syntax
(drozer) bash-3.2$ python2 --version
```

**Comment by fujiokayu** [comment]
Hi @vinilnarayan, Thanks for reporting this Issue.

I haven't maintained this repository for a while and don't plan to do so in the future, but I can offer some advice.

## 1. use the Docker version of Drozer.

I have not used it, but you can use the Docker version of Drozer now.
Please refer to [this page](https://github.com/FSecureLABS/drozer/tree/develop/docker) for more information.

## 2. do not use Drozer

As stated at [the beginning of the README](https://github.com/FSecureLABS/drozer#note), Drozer is no longer maintained.
The OWASP Mobile Security Testing Guide has also removed all references to Drozer as far as possible in [version 1.3.0](https://github.com/OWASP/owasp-mstg/discussions/2017) and replaced the Drozer verification procedure with a procedure using adb.

The Drozer functionality could be replaced by adb in many cases.
Please consider whether you really need Drozer.

## 3. fix Syntax Error

If for some reason you need to build Drozer yourself, you will need to resolve your syntax error mentioned above.

The print syntax error is often seen when Python 2 scripts are run on Python 3 environment.
So here is my question.
- Did you run `pipenv --python 2.x.xx` before running `pipenv shell`?
- If you run `pipenv shell` and then `python --version`, what output do you get?

**Comment by fujiokayu** [comment]
Closed due to no reply for a while.
